### ISSUE TITLE
Error: dlopen(...

### ISSUE THREAD

**Issue by anthonyneve** [LedgerHQ/ledger-live-desktop#1032]
Error was thrown:

```
Error: dlopen(/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node, 1): Library not loaded: @rpath/libledger-core.dylib
  Referenced from: /Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node
  Reason: no suitable image found.  Did find:
	/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib: code signature invalid for '/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib'

    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:1:148)
    at Object.<anonymous> (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:117:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/external "@ledgerhq/ledger-core":1:1)
    at r (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)
    at Module.module.exports.Object.defineProperty.value (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/init-libcore.js:22:7)
    at r (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)
    at Ve (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/withLibcore.js:14:9)
    at p.f [as impl] (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/commands/libcoreGetVersion.js:18:31)
    at process.on.e (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/internals/index.js:69:17)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at process.emit (/Users/anthony/Desktop/Ledger Live.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:454:21)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by anthonyneve** [comment]
vires in numeris what does that mean

**Comment by KhalilBellakrid** [comment]
@anthonyneve could you please provide your MacOS version ?

**Comment by balthazar** [comment]
Unrelated to your issue, "Vires in numeris" stands for "Strength in numbers" in Latin.

**Comment by hughlaw** [comment]
Also getting this error - using Mac OS X 10.10.5 (Yosemite)
Came across a similar [issue with Atom](https://github.com/atom/atom/issues/17565) which also happens to be an Electron app. Not sure if they are related but the Atom issue has been resolved.

**Comment by gre** [comment]
the bug seems to happen for mac version 10.10.x  and 10.9.x. We're building the app from 10.13.5 and this might cause problem.
now looking at ways to solve this..
