### ISSUE TITLE
Error: Internal process error (3765269347)

### ISSUE THREAD

**Issue by natnet1** [LedgerHQ/ledger-live-desktop#1036]
Error was thrown:

```
Error
    at o (file:///C:/Users/FELHAS~1/AppData/Local/Temp/Rar$EXa7584.6692/resources/app.asar/webpack:/src/helpers/errors.js:11:10)
    at a (file:///C:/Users/FELHAS~1/AppData/Local/Temp/Rar$EXa7584.6692/resources/app.asar/webpack:/src/helpers/errors.js:31:14)
    at EventEmitter.l (file:///C:/Users/FELHAS~1/AppData/Local/Temp/Rar$EXa7584.6692/resources/app.asar/webpack:/src/helpers/ipc.js:61:23)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
```

**Comment by gre** [comment]
#933
