### ISSUE TITLE
Error: No device given

### ISSUE THREAD

**Issue by pietro59** [LedgerHQ/ledger-live-desktop#1041]
Error was thrown:

```
Invariant Violation: No device given
    at invariant (C:\Program Files\Ledger Live\resources\app.asar\node_modules\invariant\invariant.js:40:15)
    at component.render (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:16:265996)
    at Kg (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:226)
    at Rg (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:180:75)
    at xh (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:202:22)
    at yh (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:203:234)
    at Vh (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:212:353)
    at Yh (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:278)
    at Wh (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:211:113)
    at Ah (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:209:281)
    at og (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:207:333)
    at Object.enqueueSetState (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:148:225)
    at Connect.F.setState (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at Connect.onStateChange (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:222:16)
    at Object.notify (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at Object.notify (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:30:21)
    at Subscription.notifyNestedSubs (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\utils\Subscription.js:69:20)
    at Connect.onStateChange (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-redux\lib\components\connectAdvanced.js:219:16)
    at dispatch (C:\Program Files\Ledger Live\resources\app.asar\node_modules\redux\lib\redux.js:227:7)
    at n (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:16:106352)
    at n (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:63:52646)
    at n (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:63:52802)
    at t (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:175610)
    at C:\Program Files\Ledger Live\resources\app.asar\node_modules\redux-thunk\lib\index.js:14:16
    at Object.dispatch (C:\Program Files\Ledger Live\resources\app.asar\node_modules\react-router-redux\middleware.js:18:18)
    at SafeSubscriber.B.send.subscribe [as _next] (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:178623)
    at SafeSubscriber.__tryOrUnsub (C:\Program Files\Ledger Live\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Program Files\Ledger Live\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\Program Files\Ledger Live\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:87:26)
    at Subscriber.next (C:\Program Files\Ledger Live\resources\app.asar\node_modules\rxjs\internal\Subscriber.js:64:18)
    at EventEmitter.l (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/renderer.js:1:26887)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
```

**Comment by pietro59** [comment]
I  parcese  this  devise  some  month  ago  to  day  first  try  to  set  up  to  run  but  no  possible  always  errro  message   ,no  way  to  work  at   all
