### ISSUE TITLE
Error: Internal process error (3765269347)

### ISSUE THREAD

**Issue by dimka7777** [LedgerHQ/ledger-live-desktop#1059]
Error was thrown:

```
Error
    at o (file:///D:/ledgerwallet/resources/app.asar/webpack:/src/helpers/errors.js:11:10)
    at a (file:///D:/ledgerwallet/resources/app.asar/webpack:/src/helpers/errors.js:31:14)
    at EventEmitter.l (file:///D:/ledgerwallet/resources/app.asar/webpack:/src/helpers/ipc.js:61:23)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
```

**Comment by gre** [comment]
#933
