### ISSUE TITLE
Error: Library not loaded: @rpath/libledger-core.dylib  Referenced from: ....

### ISSUE THREAD

**Issue by funoverip** [LedgerHQ/ledger-live-desktop#1094]
Hi,

I can start the new Ledger Live app :(

Error was thrown:

```
Error: dlopen(/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node, 1): Library not loaded: @rpath/libledger-core.dylib
  Referenced from: /Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/ledger-core-node.node
  Reason: no suitable image found.  Did find:
	/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib: code signature invalid for '/Applications/Ledger Live.app/Contents/Resources/app.asar.unpacked/node_modules/@ledgerhq/ledger-core/build/Release/libledger-core.dylib'

    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:1:148)
    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/ledger-core/js/index.js:117:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/external "@ledgerhq/ledger-core":1:1)
    at r (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)
    at Module.module.exports.Object.defineProperty.value (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/init-libcore.js:22:7)
    at r (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/webpack/bootstrap:37:1)
    at Ve (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/helpers/withLibcore.js:14:9)
    at p.f [as impl] (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/commands/libcoreGetVersion.js:18:31)
    at process.on.e (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/src/internals/index.js:69:17)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at process.emit (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:454:21)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```
Environment:
- MacBook Pro (Retina, 15-inch, Mid 2014)
- Yosemite 10.10.5

**Comment by funoverip** [comment]
Awesome . Thanks !
