### ISSUE TITLE
Debian stretch build error: ledger-live-desktop/node_modules/usb: Command failed.

### ISSUE THREAD

**Issue by jcalfee** [LedgerHQ/ledger-live-desktop#1527]
#### Ledger Live Version and Operating System

v1.1.11 Build Error
Debian GNU/Linux 9 (stretch)

#### Expected behavior

Build Success

#### Actual behavior

Error below

#### Steps to reproduce the behavior

```bash
$ nvm current
v8.12.0

$ python 
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2

$ yarn version
yarn version v1.9.4
info Current version: 1.1.11

$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


ledger-live-desktop$ yarn
yarn install v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > downshift@1.31.16" has unmet peer dependency "prop-types@>=15".
warning " > react-spring@5.3.18" has unmet peer dependency "prop-types@15.x.x".
warning "@storybook/react > babel-loader@7.1.4" has incorrect peer dependency "babel-core@6".
[4/4] Building fresh packages...
[6/14] ⡀ @ledgerhq/ledger-core
[2/14] ⢀ usb
[-/14] ⢀ waiting...
[4/14] ⢀ secp256k1
error /home/james/opt/ledger-live-desktop/node_modules/usb: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/james/opt/ledger-live-desktop/node_modules/usb
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.2
node-pre-gyp info using node@8.12.0 | linux | x64
node-pre-gyp info check checked for "/home/james/opt/ledger-live-desktop/node_modules/usb/src/binding/usb_bindings.node" (not found)
node-pre-gyp http GET https://github.com/tessel/node-usb/releases/download/1.3.2/usb_bindings-v1.3.2-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.3.2/usb_bindings-v1.3.2-node-v57-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.2/usb_bindings-v1.3.2-node-v57-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.2 and node@8.12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/tessel/node-usb/releases/download/1.3.2/usb_bindings-v1.3.2-node-v57-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.12.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.12.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/james/opt/ledger-live-desktop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/james/opt/ledger-live-desktop/node_modules/usb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/james/opt/ledger-live-desktop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/james/.node-gyp/8.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/james/.node-gyp/8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/james/opt/ledger-live-desktop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/james/.node-gyp/8.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/james/opt/ledger-live-desktop/node_modules/usb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.12.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/james/opt/ledger-live-desktop/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
                     ^
compilation terminated.
libusb.target.mk:140: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: Leaving directory '/home/james/opt/ledger-live-desktop/node_modules/usb/build'
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/james/opt/ledger-live-desktop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/home/james/.nvm/versions/node/v8.12.0/bin/node" "/home/james/opt/ledger-live-desktop/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/james/opt/ledger-live-desktop/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/james/opt/ledger-live-desktop/node_modules/usb/src/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/james/opt/ledger-live-desktop/node_modules/usb
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/james/.nvm/versions/node/v8.12.0/bin/node /home/james/opt/ledger-live-desktop/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/james/opt/ledger-live-desktop/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/james/opt/ledger-live-desktop/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/james/opt/ledger-live-desktop/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.9.0-8-amd64
node-pre-gyp ERR! command "/home/james/.nvm/versions/node/v8.12.0/bin/node" "/home/james/opt/ledger-live-desktop/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/james/opt/ledger-live-desktop/node_modules/usb
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.2




[[ hangs until ctrl+c ]]
```

**Comment by jcalfee** [comment]
Do you have a docker build?  Or any alternative that would allow me to build my own installer or code..  The goal is simply to build run from code (installed or not).

**Comment by meriadec** [comment]
Hey there! Take a look at [the CircleCI config](https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/.circleci/config.yml) it should provide some useful hints (it uses stretch also). Also ensure that you are running Node.js LTS and Python 2.7

**Comment by jcalfee** [comment]
Hi!  For starters I was missing this:  `sudo apt install libudev-dev` ..

O yea, circle..  thanks
