### ISSUE TITLE
can't open device

### ISSUE THREAD

**Issue by jcalfee** [LedgerHQ/ledger-live-desktop#1528]
#### Ledger Live Version and Operating System

v1.1.11

PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

#### Actual behavior

Can't connect to the device

#### Steps to reproduce the behavior

After successfully entering the PIN, the UI says `Oops, couldn’t connect to device` .. The Ledger Nano display shows some icons of coins so that part looks fine.

```bash
┏ Electron -------------------

  debug: Device add detected: {"type":"listenDevices","args":[{"busNumber":1,"deviceAddress":27,"deviceDescriptor":{"bLength":18,"bDescriptorType":1,"bcdUSB":512,"bDeviceClass":0,"bDeviceSubClass":0,"bDeviceProtocol":0,"bMaxPacketSize0":64,"idVendor":11415,"idProduct":1,"bcdDevice":512,"iManufacturer":1,"iProduct":2,"iSerialNumber":3,"bNumConfigurations":1},"portNumbers":[2]}],"pname":"internal","timestamp":"2018-09-19T19:14:49.634Z"}

┗ ----------------------------
┏ Electron -------------------

  debug: Polling for added or removed devices {"type":"listenDevices","args":[],"pname":"internal","timestamp":"2018-09-19T19:14:49.836Z"}

┗ ----------------------------
┏ Electron -------------------

  debug: New device found: {"type":"listenDevices","args":[["/dev/hidraw4"]],"pname":"internal","timestamp":"2018-09-19T19:14:49.838Z"}

┗ ----------------------------
┏ Electron -------------------

  debug: No removed device found {"type":"listenDevices","args":[],"pname":"internal","timestamp":"2018-09-19T19:14:49.840Z"}

┗ ----------------------------
┏ Electron -------------------

  warn: retry failed {"pname":"internal","timestamp":"2018-09-19T19:14:49.924Z"}

┗ ----------------------------
┏ Electron -------------------

  warn: retry failed {"pname":"internal","timestamp":"2018-09-19T19:14:50.226Z"}

┗ ----------------------------
┏ Electron -------------------

  warn: Command error: {"name":"CantOpenDevice","stack":"Error\n    at CustomError (webpack-internal:///./src/helpers/errors.js:13:18)\n    at mapError (webpack-internal:///./src/helpers/deviceAccess.js:21:11)\n    at <anonymous>","pname":"internal","timestamp":"2018-09-19T19:14:50.680Z"}

┗ ----------------------------
```

**Comment by gre** [comment]
Have you tried to follow the Linux specific instruction to make the usb work with Ledger devices (udev rules, etc)?

https://support.ledgerwallet.com/hc/en-us/articles/115005165269-Fix-connection-issues

thanks

**Comment by jcalfee** [comment]
It was udev rules .. Great, glad to have this working thank you .. Thanks for adding EOS!
