### ISSUE TITLE
SSH/PGP Agent with Ledger Nano S possible to run on Windows?

### ISSUE THREAD

**Issue by eastabrooka** [LedgerHQ/ledger-live-desktop#1675]
#### Ledger Live Version and Operating System

- tested on Ledger Live **1.2.6**
- Platform and version: ** Windows 10 17134 .**
Device Firmware 1.4.2 
Python 3.6.0 (v3.6.0:41df79263a11,

#### Expected behavior

I was reading the guide here : https://trello.com/c/lzrZ7Vyv/29-ssh-gpg-agent-app after just buying a Ledger Nano to keep my SSH Keys safe. 

I was hoping that by doing 
>python -m pip install --upgrade pip
>pip install --upgrade setuptools
>pip install libusb

and then pip3 install ledger-agent - id be able to leverage all the Ledger-agent SSH Tools from inside windows. 

What i actually got was 

#### Actual behavior

Collecting ledger-agent
  Using cached https://files.pythonhosted.org/packages/a3/c9/ac7546d6168662af356493231ca8818bdf8ffd05238a68fe5085fd9e6358/ledger_agent-0.9.0.tar.gz
Collecting libagent>=0.9.0 (from ledger-agent)
  Using cached https://files.pythonhosted.org/packages/5f/e2/f18cee65d480b66953e5a5ed9093c8a8e24d39011d6520dbbff262d6aead/libagent-0.12.1.tar.gz
Collecting ledgerblue>=0.1.8 (from ledger-agent)
  Using cached https://files.pythonhosted.org/packages/3c/62/39d9b29f5ada49a0ec595e275d5326dd9e6f94939138884506a4105dcedb/ledgerblue-0.1.21.tar.gz
Collecting backports.shutil_which>=3.5.1 (from libagent>=0.9.0->ledger-agent)
  Using cached https://files.pythonhosted.org/packages/3d/1b/136e8ffa98ce077e12afde6c333eb2b61266e0de0e404ec7a0c47b8f8a8b/backports.shutil_which-3.5.2-py2.py3-none-any.whl
Collecting ConfigArgParse>=0.12.1 (from libagent>=0.9.0->ledger-agent)
  Using cached https://files.pythonhosted.org/packages/77/61/ae928ce6ab85d4479ea198488cf5ffa371bd4ece2030c0ee85ff668deac5/ConfigArgParse-0.13.0.tar.gz
Collecting python-daemon>=2.1.2 (from libagent>=0.9.0->ledger-agent)
  Using cached https://files.pythonhosted.org/packages/99/2a/75fe6aa7086e838570f29899f674e7896a42be26d9fff33f90d990e599d2/python-daemon-2.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-22kq7ppc\python-daemon\setup.py", line 34, in <module>
        level=0, fromlist=main_module_fromlist)
      File "C:\Users\User\AppData\Local\Temp\pip-install-22kq7ppc\python-daemon\daemon\__init__.py", line 38, in <module>
        from .daemon import DaemonContext
      File "C:\Users\User\AppData\Local\Temp\pip-install-22kq7ppc\python-daemon\daemon\daemon.py", line 19, in <module>
        import pwd
    ModuleNotFoundError: No module named 'pwd'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\User\AppData\Local\Temp\pip-install-22kq7ppc\python-daemon\

#### Steps to reproduce the behavior

I am starting to feel that the OpenPGP / SSH Key side of life on the Ledger Nano S is a bit limited. I was reading the docs at https://github.com/LedgerHQ/ledger-app-openpgp-card/blob/master/doc/user/blue-app-openpgp-card.pdf - and finding that the Windows section is still TODO. 

Having just purchased this device for non-crypto purposes, and primarily being a windows user - I am worried that I wont be able to use it for this. 

Is this the case ?

**Comment by eastabrooka** [comment]
Closing out - Because i should have raised this on ledger-app-ssh-agent. sorry.
