### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by dgaus** [LedgerHQ/ledger-live-desktop#1956]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.7.0
- Platform and version: Linux AppImage

#### Expected behavior

Ledger Live should synchronize correctly

#### Actual behavior

It gets stuck in a loop trying to synchronize while printing an error at the top

Relevant log entries:
```
 {
    "level": "error",
    "message": "API HTTP 403",
    "method": "GET",
    "name": "LedgerAPI4xx",
    "pname": "renderer",
    "stack": "Error\n    at CustomError (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:20:18)\n    at p (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:16:7)\n    at t.catch.t (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:50:24)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
    "status": 403,
    "timestamp": "2019-04-27T01:01:14.405Z",
    "url": "https://explorers.api.live.ledger.com/blockchain/v2/vtc/syncToken"
  },
  {
    "data": {
      "message": "API HTTP 403",
      "method": "GET",
      "name": "LedgerAPI4xx",
      "stack": "Error\n    at CustomError (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:20:18)\n    at p (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:16:7)\n    at t.catch.t (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:50:24)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
      "status": 403,
      "url": "https://explorers.api.live.ledger.com/blockchain/v2/vtc/syncToken"
    },
    "level": "warn",
    "message": "✖ CMD libcoreSyncAccount error",
    "pname": "renderer",
    "timestamp": "2019-04-27T01:01:14.405Z",
    "type": "cmd.ERROR"
  },
  {
    "data": {
      "message": "API HTTP 403",
      "method": "GET",
      "name": "LedgerAPI4xx",
      "stack": "Error\n    at CustomError (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:20:18)\n    at p (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:16:7)\n    at t.catch.t (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:50:24)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
      "status": 403,
      "url": "https://explorers.api.live.ledger.com/blockchain/v2/vtc/syncToken"
    },
    "level": "warn",
    "message": "✖ CMD libcoreSyncAccount error",
    "pname": "internal",
    "timestamp": "2019-04-27T01:01:14.404Z",
    "type": "cmd.ERROR"
  },
  {
    "error": {
      "message": "API HTTP 403",
      "method": "GET",
      "name": "LedgerAPI4xx",
      "stack": "Error\n    at CustomError (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:20:18)\n    at p (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:16:7)\n    at t.catch.t (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:50:24)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
      "status": 403,
      "url": "https://explorers.api.live.ledger.com/blockchain/v2/vtc/syncToken"
    },
    "level": "warn",
    "message": "Command error:",
    "pname": "internal",
    "timestamp": "2019-04-27T01:01:14.404Z"
  },
  {
    "level": "debug",
    "message": "syncAccountEvent 4",
    "pname": "internal",
    "timestamp": "2019-04-27T01:01:14.403Z",
    "type": "libcore-sync"
  },
  {
    "level": "error",
    "message": "🛠  2019-04-26T22:01:14Z-03:00 E: Due to EC_PRIV_KEY_INVALID_FORMAT, {\"status\":403,\"url\":\"https://explorers.api.live.ledger.com/blockchain/v2/vtc/syncToken\",\"method\":\"GET\",\"name\":\"LedgerAPI4xx\",\"message\":\"API HTTP 403\",\"stack\":\"Error\\n    at CustomError (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:20:18)\\n    at p (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:16:7)\\n    at t.catch.t (/tmp/.mount_ledgeriYNijy/app/resources/app.asar/dist/internals/webpack:/src/api/network.js:50:24)\\n    at <anonymous>\\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\"} (EC_PRIV_KEY_INVALID_FORMAT)\n",
    "pname": "internal",
    "timestamp": "2019-04-27T01:01:14.403Z",
    "type": "libcore"
  },
```

Afterwards it repeats changing the coin in the URL, it's not specific to VTC.
I have tried clearing the cache to no avail. It used to work correctly but I am not sure what particular update broke this. Thanks.

**Comment by gre** [comment]
This looks like a backend issue to me, can you contact our tech support so we gets it reported to the correct team? thanks

**Comment by dgaus** [comment]
Tech support wasn't really helpful. I managed to get it working by using my phone as a hotspot without any other changes, so here is a description of what I believe the problem is: 
- Ledger live tries to hit an API endpoint
- The request goes through CloudFlare, which offers DDOS protection
- If CloudFlare considers the request to be suspicious, it returns a HTTP 403 FORBIDDEN error

If the application could detect this case and open a Webkit window or similar, the user could solve the CAPTCHA and CloudFlare would let the request go through (and hopefully flag it as safe for future requests).

I also think people on https://github.com/LedgerHQ/ledger-live-desktop/issues/1035 could be facing the same issue.
