### ISSUE TITLE
I'm trying to run the ledger-live-desktop so I can build and test against a fork of `ledger-live-common` and getting an error

### ISSUE THREAD

**Issue by mxaddict** [LedgerHQ/ledger-live-desktop#2011]
I'm trying to run the ledger-live-desktop so I can build and test against a fork of `ledger-live-common` and getting an error: 
```
InternalError: Internal process error (null)
Error
    at createCustomErrorClass (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/@ledgerhq/errors/src/helpers.js:24:17)
    at deserializeError (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/@ledgerhq/errors/src/helpers.js:55:25)
    at EventEmitter.handleCommandEvent (webpack-internal:///./src/helpers/ipc.js:93:100)
    at emitTwo (events.js:131:20)
    at EventEmitter.emit (events.js:214:7)
redux failed: Invariant Violation: Could not find "store" in either the context or props of "Connect(Modal)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Modal)".
Invariant Violation: Could not find "store" in either the context or props of "Connect(Modal)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Modal)".
    at invariant (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/invariant/invariant.js:40:15)
    at new Connect (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-redux/lib/components/connectAdvanced.js:134:33)
    at constructClassInstance (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:11361:18)
    at updateClassComponent (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:14687:5)
    at beginWork (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:15644:16)
    at performUnitOfWork (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:19312:12)
    at workLoop (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:19352:24)
    at renderRoot (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:19435:7)
    at performWorkOnRoot (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:20342:7)
    at performWork (/home/mxaddict/Projects/mxaddict/ledger-live-desktop/node_modules/react-dom/cjs/react-dom.development.js:20254:7)
```

I'm running:
Node: v8.9.4
Yarn: 1.16.0

**Comment by gre** [comment]
what is the error in the console terminal?

If running in Linux, you might want to locally `yarn add electron@1.8.8` . that's our current workaround for a bug we have in linux (tcmalloc free pointer crash)

**Comment by mxaddict** [comment]
Yes, I did see a pointer crash before the above error occurred.

I'll try that now, thanks for the quick response @gre

**Comment by mxaddict** [comment]
Thanks, the fix worked, Is there a reason why the electron version is not locked in the package.json?

**Comment by mxaddict** [comment]
@gre am I doing this right?

I've created a fork of ledger-live-common, and want to use it on my ledger-live-desktop

I've run this: `yarn add git+https://github.com/mxaddict/ledger-live-common.git `

It's adding the package just fine, but when running `yarn start`

I get these:
```
ERROR in ./src/commands/libcoreScanAccounts.js                                                                                                                                                 
Module not found: Error: Can't resolve '@ledgerhq/live-common/lib/account' in '/home/mxaddict/Projects/mxaddict/ledger-live-desktop/src/commands'
 @ ./src/commands/libcoreScanAccounts.js 5:0-65 9:94-106
 @ ./src/commands/index.js
 @ ./src/main/commandHandler.js
 @ ./src/internals/index.js

ERROR in ./src/commands/libcoreSignAndBroadcast.js
Module not found: Error: Can't resolve '@ledgerhq/live-common/lib/account' in '/home/mxaddict/Projects/mxaddict/ledger-live-desktop/src/commands'
 @ ./src/commands/libcoreSignAndBroadcast.js 2:0-104 6:11-25 7:38-57 12:22-36
 @ ./src/commands/index.js
 @ ./src/main/commandHandler.js
 @ ./src/internals/index.js
```

**Comment by gre** [comment]
@mxaddict yeah it's a ugly temporary solution at the moment. the reason is that Mac requires us to use electron@2 because we have a fix for Mac and a custom version of electron-updater. Ideally we should fix it in Linux. Even better we'll eventually migrate to latest Electron version at some point in the future 🤞 

mmh I'm not sure live-common is installable with a github link. it sounds like the /lib folder is not getting built (because it's a `prepublish` i suppose). I'm not sure what's the best set up to get this work locally. I'm not sure that `yarn link` works for instance because it tends to create dependency duplicate problem. myself, I tend to `rsync` my node_modules live-common/lib folder into node_modules, but I know @juan-cortes is fan of http://npmjs.com/package/wml which have some overhead but do the job.

**Comment by mxaddict** [comment]
I see, so I might be able to build the package locally and then do a `yarn add file:../path` should work?

**Comment by gre** [comment]
it should work too yes

**Comment by mxaddict** [comment]
> it should work too yes

One issue, `yarn build` on my local `ledger-live-common` is failing with:
```
yarn run v1.16.0
$ rm -rf lib src/data/icons/react* && node scripts/buildPartnersReactLogos.js && node scripts/buildReactIcons.js && babel --ignore __tests__ -sd lib src && flow-copy-source -i "__tests__/**" src lib
module.js:540
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mxaddict/Projects/mxaddict/ledger-live-common/scripts/buildPartnersReactLogos.js:2:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
error Command failed with exit code 1.
```

**Comment by mxaddict** [comment]
I found the issue with the yarn build for local live-common :+1: 

Thanks for the help @gre

**Comment by mxaddict** [comment]
@gre so I've added the currency to my fork https://github.com/mxaddict/ledger-live-common

And am now able to run the `ledger-live-desktop` app locally with the forked library.

But I can't seem to see the new currency added to the list of currencies under "Add Account"?

Am I missing something else that needs modification to add new currencies to ledger-live app?

**Comment by mxaddict** [comment]
My PR is here for reference: https://github.com/LedgerHQ/ledger-live-common/pull/252

**Comment by gre** [comment]
@mxaddict Live Desktop and Mobile use the https://github.com/LedgerHQ/lib-ledger-core library which deals with all cryptocurrencies related (including xpub, so we don't generate the xpub on JS side regarding your question on ledgerjs). cryptocurrencies whitelist is currently here: https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/config/cryptocurrencies.js

**Comment by mxaddict** [comment]
Thanks for the info!
