### ISSUE TITLE
HTTP 500 error sync ETC app

### ISSUE THREAD

**Issue by sasij** [LedgerHQ/ledger-live-desktop#2607]
Hi

After installing the ETC app, I tap on add account, but it is stuck in the third step with a 500 HTTP error code.

- ledger nano S with 1.6.0
- Ledger live desktop with 1.20
- OS Catalina 1.15.3

Any help?
Thanks.

I found in the logs the next traces:
```json 
{
"level": "error",
"message": "API HTTP 500",
"method": "GET",
"name": "LedgerAPI5xx",
"pname": "renderer",
"stack": "Error\n    at new CustomError (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:25:18)\n    at T (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/node_modules/tslib/tslib.es6.js:17:1)\n    at e.catch.e (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/node_modules/tslib/tslib.es6.js:17:1)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
"status": 500,
"timestamp": "2020-02-21T20:15:38.364Z",
"url": "https://explorers.api.live.ledger.com/blockchain/v3/etc/addresses/<HIDDEN>/balance"
},
{
"data": {
            "message": "API HTTP 500",
            "method": "GET",
            "name": "LedgerAPI5xx",
            "stack": "Error\n    at new CustomError (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:25:18)\n    at T (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/node_modules/tslib/tslib.es6.js:17:1)\n    at e.catch.e (/Applications/Ledger Live.app/Contents/Resources/app.asar/dist/internals/webpack:/node_modules/tslib/tslib.es6.js:17:1)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)",
            "status": 500,
            "url": "https://explorers.api.live.ledger.com/blockchain/v3/etc/addresses/<HIDDEN>/balance"
        },
"level": "warn",
"message": "✖ CMD CurrencyScanAccountsOnDevice error",
"pname": "renderer",
"timestamp": "2020-02-21T20:15:38.364Z",
"type": "cmd.ERROR"
}

**Comment by sasij** [comment]
It seems to be fixed now.

**Comment by clintnetwork** [comment]
is it too difficult to maintain an API up? for the ledger price you can I think

<img width="698" alt="Screenshot 2021-09-02 at 13 26 36" src="https://user-images.githubusercontent.com/5221349/131827961-55ee0077-e555-4e21-a59a-cb2ecd20d9ee.png">
