### ISSUE TITLE
Ledger Live fails to render UI

### ISSUE THREAD

**Issue by theogravity** [LedgerHQ/ledger-live-desktop#2663]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.20.0
- Platform and version: OS X 10.14.6 (18G87)

#### Expected behavior

App UI should show up.

#### Actual behavior

App gives stack trace:

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at Object.render (file:///Applications/Ledger%20Live.app/Contents/Resources/app.asar/renderer.js:64:612335)
    at vi (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:181:192)
    at ui (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:180:282)
    at gk (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:261:396)
    at fk (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:230:22)
    at Zj (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:229:362)
    at Lj (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:223:216)
    at /Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:121:115
    at exports.unstable_runWithPriority (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js:18:438)
    at fg (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:120:325)
    at ig (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:121:61)
    at jg (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:120:496)
    at fb (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:283:237)
    at Nd (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:82:277)
    at HTMLDocument.wrapped (/Applications/Ledger Live.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:377:21)
```

#### Steps to reproduce the behavior

Transferred all DAI out of my hardware wallet. Ledger Live then presented the following screen.

![image](https://user-images.githubusercontent.com/855434/75719319-6865d300-5c89-11ea-8f5c-bfb9469cf60d.png)

- Attempted restart with same results
- Performed reset option, using existing nano x wallet as import, same result.

**Comment by gre** [comment]
@theogravity Hi and thanks for the issue. Could you try if our upcoming version 2.0.0 is able to fix the problem? https://github.com/LedgerHQ/ledger-live-desktop/releases

otherwise you might want to try a Reset if it is still blocking in that state (that reset your accounts so you will have to reimport them with the device)

**Comment by theogravity** [comment]
I'm unsure what I did, re-opening the app today fixed the issue.
