### ISSUE TITLE
[Linux] Ledger Live 2.0.0 doesn't start

### ISSUE THREAD

**Issue by etale-cohomology** [LedgerHQ/ledger-live-desktop#2686]
#### Ledger Live Version and Operating System

- tested on Ledger Live **2.0.0**
- Platform and version: **Ubuntu 18.04.3 LTS Linux 4.15.0-88-generic**

#### Expected behavior

The Ledger Live program should start.

#### Actual behavior

The Ledger Live program doesn't start.

#### Steps to reproduce the behavior

Download **Ledger Live 2.0.0**.
Run Ledger Live 2.0.0.
An error screen appears with the following errors:

```
Internal process error (1)
Error
    at createCustomErrorClass (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:9690:17)
    at deserializeError (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:9723:25)
    at EventEmitter.handleCommandEvent (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:257897:61)
    at EventEmitter.emit (events.js:210:5)
    at Object.onMessage (electron/js2c/renderer_init.js:2181:16)

redux failed: Cannot read property 'store' of null
TypeError: Cannot read property 'store' of null
    at ConnectFunction (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:560:70)
    at Ih (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157129:98)
    at si (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157149:273)
    at ri (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157149:103)
    at pi (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157148:178)
    at gk (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157241:63)
    at fk (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157205:22)
    at Zj (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157204:362)
    at Lj (file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157198:216)
    at file:///tmp/.mount_ledgern0BKf1/resources/app.asar/.webpack/renderer.bundle.js:157096:115
```

**Comment by Zizaerion** [comment]
It looks like they've got a new update that they'll be releasing in a day or two to fix this issue.  you can also download it early it's version 2.0.1

**Comment by gre** [comment]
@etale-cohomology Can you please check if 2.0.1 fixes this? If it still doesn't, I suggest we close it in favor of #2685 

In any case it would be good if you could export the logs (SAVE) and provide it to our tech support at https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165 

thanks
