### ISSUE TITLE
[Ethereum/Browser Support] TransportInterfaceNotAvailable: The interface number provided is not supported by the device in its current configuration.

### ISSUE THREAD

**Issue by michaelhly2** [LedgerHQ/ledger-live-desktop#2687]
####  Ledger Live Version and Operating System
Device: Ledger Nano S
Firmware: 1.4.2
Ledger Live Version: 1.20.0
Platform and version: Mac 10.14.5
Ledger Ethereum App: 1.1.8

#### Expected behavior
Select Ethereum wallet based on depravation path.  

#### Actual behavior

![Actual Behavior](https://i.imgur.com/2ZVeQTd.png)

#### Steps to reproduce the behavior
Try connecting ledger wallet with MyCrypto.

**Comment by michaelhly2** [comment]
This was working when using Ethereum App 1.1.4.

**Comment by michaelhly2** [comment]
Same problem when trying to send a transaction via the Metamask extension.

**Comment by michaelhly** [comment]
From the metamask state logs:
```
[
...
            {
              "op": "add",
              "path": "/err",
              "value": {
                "message": "Error: TransportStatusError: Ledger device: Invalid data received (0x6a80)",
                "stack": "Error: TransportStatusError: Ledger device: Invalid data received (0x6a80)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:175741\n    at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:177311)\n    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:238573)"
              },
              "note": "transactions:tx-state-manager#fail - add error",
              "timestamp": 1583462267323
            }
...
]
```
