### ISSUE TITLE
Error when Opening Ledger Live 2.0.1

### ISSUE THREAD

**Issue by Donoghue23** [LedgerHQ/ledger-live-desktop#2774]
#### Ledger Live Version and Operating System

Ledger Live 2.0.1

- tested on Ledger Live **2.0.1**
- Platform and version: **Windows 8.**

#### Expected behavior

<When I open the app I get an error message.  (Below) I then can click restart and it will work.  However when I then connect my Nano S to my laptop the app and the hardware do not interact and I was thinking it may be related to the error issue when opening the App -->

#### Internal process error (1)

Below Error message shows when opening the App
Error
    at createCustomErrorClass (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9690:17)
    at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:9723:25)
    at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:257937:61)
    at EventEmitter.emit (events.js:215:7)
    at Object.onMessage (electron/js2c/renderer_init.js:2181:16)
redux failed: Cannot read property 'store' of null
TypeError: Cannot read property 'store' of null
    at ConnectFunction (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:560:70)
    at Ih (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157157:98)
    at si (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:273)
    at ri (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157177:103)
    at pi (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157176:178)
    at gk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157269:63)
    at fk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157233:22)
    at Zj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157232:362)
    at Lj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157226:216)
    at file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:157124:115

<I would like you to possibly give me some guidance how I can fix this problem to hopefully allow me to use my Nano S -->

Thanks

**Comment by gre** [comment]
dup https://github.com/LedgerHQ/ledger-live-desktop/issues/2680
