### ISSUE TITLE
Chyba při spuštění Ledger Live

### ISSUE THREAD

**Issue by Milcek88** [LedgerHQ/ledger-live-desktop#2797]
Oops, something went wrong You may try again by restarting Ledger Live. Please export your logs and contact Ledger Support if the problem persists.

Internal process error (1)
Error
    at createCustomErrorClass (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:9690:17)
    at deserializeError (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:9723:25)
    at EventEmitter.handleCommandEvent (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:257937:61)
    at EventEmitter.emit (events.js:215:7)
    at Object.onMessage (electron/js2c/renderer_init.js:2181:16)
redux failed: Cannot read property 'store' of null
TypeError: Cannot read property 'store' of null
    at ConnectFunction (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:560:70)
    at Ih (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157157:98)
    at si (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157177:273)
    at ri (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157177:103)
    at pi (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157176:178)
    at gk (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157269:63)
    at fk (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157233:22)
    at Zj (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157232:362)
    at Lj (file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157226:216)
    at file:///C:/Program%20Files%20(x86)/Ledger%20live/resources/app.asar/.webpack/renderer.bundle.js:157124:115

#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**

**Comment by Milcek88** [comment]
kam mám případně přiložit přílohu print screnu?

**Comment by Milcek88** [comment]
případně odpověď prosím na email . děkuji
