### ISSUE TITLE
AppImage launch of Ledger Live with Ledger Nano X on Debian Buster fails to detect

### ISSUE THREAD

**Issue by gebyt-rybrit** [LedgerHQ/ledger-live-desktop#3485]
2.19/2.20 live appimage fails to detect my ledger nano x

Tried AppImage v2.19 - device would not detect when plugged in, Found below link:

https://github.com/LedgerHQ/ledger-live-desktop/issues/3408

attempted to try 2.20 App Image, still fails to detect.

lsusb shows the device ID upon physical connection

lsusb -v shows message for the same device ID as :

Bus 001 Device 007: ID XXXX:XXXX  
Couldn't open device, some information will be missing

JSON logs when I click the 'get logs' button shows errors like below:

level":"info","pname":"renderer","timestamp":"2021-01-19T01:14:54.951Z"},{"type":"cmd.ERROR","data":{"name":"CantOpenDevice","message":"cannot open device with path /dev/hidraw0","stack":"Error\n    at new CustomError (/tmp/.mount_ledgernZB0ZQ/resources/app.asar/node_modules/@ledgerhq/errors/dist/index.cjs.js:19:22)\n    at /tmp/.mount_ledgernZB0ZQ/resources/app.asar/node_modules/@ledgerhq/live-common/lib/hw/deviceAccess.js:107:11"},"level":"info","message":"✖ CMD connectManager error","pname":"renderer","timestamp":"2021-01-19T01:14:54.950Z"},{"type":"cmd.ERROR","data":{"name":"CantOpenDevice","message":"cannot open device with path /dev/hidraw0","stack":"Error\n    at new CustomError (/tmp/.mount_ledgernZB0ZQ/resources/app.asar/node_modules/@ledgerhq/errors/dist/index.cjs.js:19:22)\n    at /tmp/.mount_ledgernZB0ZQ/resources/app.asar/node_modules/@ledgerhq/live-common/lib/hw/deviceAccess.js:107:11"},"level":"warn","message":"✖ CMD connectManager error","pname":"internal","timestamp":"2021-01-19T01:14:54.945Z"},{"error":{"name":"CantOpenDevice","message":"cannot open device with path /dev/hidraw0","stack":"Error\n    at new CustomError (/tmp/.mount_ledgernZB0ZQ/resources/app.asar/node_modules/@ledgerhq/errors/dist/index.cjs.js:19:22)\n    at /tmp/.mount_ledgernZB0ZQ/resources/app.asar/node_modules/@ledgerhq/live-common/lib/hw/deviceAccess.js:107:11"},"level":"warn","message":"Command error:","pname":"internal","timestamp":"2021-01-19T01:14:54.944Z"},{"type":"hid-verbose","message":"new HID transport","level":"debug","pname":"internal","timestamp":"2021-01-19T01:14:54.944Z"},{"type":"promise-retry","message":" failed. 1 retry remain.

It rolls through multiple device tries up to 4 and fails everytime.   continued unlock/relock/disconnect/reconnect fails with same errors. 

system version:

Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-12-amd64
Architecture: x86-64

**Comment by gebyt-rybrit** [comment]
Please disregard my inquiry, I have found solution to be to run the udev script indicated on ledger support product page - 

https://support.ledger.com/hc/en-us/articles/360019301813-Fix-USB-issues

I am now able to detect and use my device properly.
