### ISSUE TITLE
[CRITICAL] SIGSEGV all the time

### ISSUE THREAD

**Issue by niso** [LedgerHQ/ledger-live-desktop#3496]
#### Ledger Live Version and Operating System

- tested on Ledger Live 2.20.0 and 2.19
- Platform and version: Ubuntu 20.04.1 LTS (Focal Fossa)

#### Expected behavior

Everything should work normally.

#### Actual behavior

I can't connect to my ledger and some of the blockchains (XRP, LTC) are not syncrhonizing and in the syncrhonizing label I can see SIGSEGV error. If I open the app from the terminal I can see this:

Ledger Live 2.20.0
(node:5962) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
init
Checking for update
spawned internal process 6068
Update for version 2.20.0 is not available (latest version: 2.20.0, downgrade is disallowed).
internal process 6068 got killed by signal SIGSEGV

And once I close the app:

(node:5962) UnhandledPromiseRejectionWarning: Error: Process not running
    at /tmp/.mount_ledgermiADUZ/resources/app.asar/.webpack/main.bundle.js:3309:16
    at new Promise (<anonymous>)
    at InternalProcess_InternalProcess.stop (/tmp/.mount_ledgermiADUZ/resources/app.asar/.webpack/main.bundle.js:3307:12)
    at App.<anonymous> (/tmp/.mount_ledgermiADUZ/resources/app.asar/.webpack/main.bundle.js:3393:20)
    at App.emit (events.js:327:22)
(node:5962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

#### Steps to reproduce the behavior

Just open the application, no matter if the ledger is connected or not.

**Comment by niso** [comment]
I'm quite disappointed by the support received...
Anyways, I've removed all the accounts I have and I narrowed the bug to Stellar.
I'm pretty sure that it happens when you have multiple tokens. Please, Could you take it a look?

**Comment by pscopic** [comment]
This bug riddled garbage is probably why I'm seeing a glut of ledgers being dumped from owners who can't use them. 

In retrospect I feel pretty silly investing any time and money on this doorstop kickstand instead of just creating my own secure cold storage unit on an air gapped usb key at a fraction of the cost. I thought picking up one of these would actually be more convenient. Boy was I wrong.

**Comment by gre** [comment]
@niso it happens as soon as you import these stellar accounts? Does the issue also occur when you haven't imported these stellar accounts in Ledger Live?

If yes, I tend to think it's a bug in our stellar implementation to support these tokens on stellar.
we plan to migrate stellar to a better implementation (js based, using stellar lib) which will fix this in future. for the time being you can use your hardware wallet with a web app like https://accountviewer.stellar.org/

**Comment by niso** [comment]
Hi @gre 

Yes, it happens only with the stellar accounts and only when they have tokens.
Thanks for the link, I was already using it.

**Comment by niso** [comment]
Any news?

**Comment by niso** [comment]
Any news?

**Comment by niso** [comment]
ANY NEWS?

**Comment by DRIX-cmd** [comment]
Following...

**Comment by gre** [comment]
2.29.0 fixes it

**Comment by arno01** [comment]
2.30.0 and getting SIGSEGV all the time :/
(I think 2.29.0 was working fine)

```
$ ledger-live-desktop-2.30.0-linux-x86_64.AppImage 
Ledger Live 2.30.0
(node:2513735) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
init
Checking for update
spawned internal process 2513926
Update for version 2.30.0 is not available (latest version: 2.30.0, downgrade is disallowed).
internal process 2513926 got killed by signal SIGSEGV
```

![Uploading image.png…]()

**Comment by PCK1992** [comment]
I have the same issue

**Comment by miloops** [comment]
> I have the same issue
> 
> ```
> Ledger Live 2.32.2
> (node:290535) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
> init
> Checking for update
> Update for version 2.32.2 is not available (latest version: 2.32.2, downgrade is disallowed).
> spawned internal process 290631
> internal process 290631 got killed by signal SIGSEGV
> ```

Having the same issue on 2.32.2 as well, Ledger Live can't connect anymore to my Nano X after this error happens.

**Comment by colourful-land** [comment]
> > I have the same issue
> > ```
> > Ledger Live 2.32.2
> > (node:290535) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
> > init
> > Checking for update
> > Update for version 2.32.2 is not available (latest version: 2.32.2, downgrade is disallowed).
> > spawned internal process 290631
> > internal process 290631 got killed by signal SIGSEGV
> > ```
> 
> Having the same issue on 2.32.2 as well, Ledger Live can't connect anymore to my Nano X after this error happens.
> 
> Edit: @gre anything I can do to help debugging?

I have this error even on Ledger Live 2.32.2 with or without Nano X plugged in.
````
Update for version 2.32.2 is not available (latest version: 2.32.2, downgrade is disallowed).
internal process 26421 got killed by signal SIGSEGV
(node:26271) UnhandledPromiseRejectionWarning: Error: Process not running
    at /tmp/.mount_ledgerL9yelF/resources/app.asar/.webpack/main.bundle.js:3382:16
    at new Promise (<anonymous>)
    at InternalProcess_InternalProcess.stop (/tmp/.mount_ledgerL9yelF/resources/app.asar/.webpack/main.bundle.js:3380:12)
    at App.<anonymous> (/tmp/.mount_ledgerL9yelF/resources/app.asar/.webpack/main.bundle.js:3466:20)
    at App.emit (events.js:327:22)
````

**Comment by quangkevin** [comment]
I tried to sync Algorand account and kept getting "Internal process killed by signal (SIGSEGV)".

**Comment by ArchiFleKs** [comment]
Still having this issue on Cosmos + Algo, and sometime other wallet too. This makes ledger live on linux unusable. I have to remove all accounts to be able to manage app.

**Comment by Stoner19** [comment]
Same behavior with Cosmos still

OS: MacOS Monterey Version 12.2.1 (21D62)
Ledger Nano S Firmware: Secure Element 2.0.2
Ledger Live Desktop 2.39.2
![Screen Shot 2022-04-01 at 3 48 11 PM](https://user-images.githubusercontent.com/8030643/161345667-8259ac1e-ccee-446d-aa58-06faa4a96a7b.png)

**Comment by karask** [comment]
Same problem here for Cosmos:

Ubuntu 20.04
Ledger Nano X (firmware 2.0.2)
Ledger Live 2.40.2

**Comment by turbamulta** [comment]
Another one with the problem. 

Ubuntu 20.04
Ledger Nano X (firmware 2.0.2)
Ledger Live 2.40.2

Started to happen after adding Cosmos in Ledger Live. BCH, which worked fine for a long time, crashed first. Removing BCH and Cosmos made Ledger Live usable again. 

Like other people said before, it seems Ledger has issues when you want to have more than a few accounts (it was just 5 in my case)
