### ISSUE TITLE
Update 2.25.1 Failed or something else?

### ISSUE THREAD

**Issue by JamesKBowler** [LedgerHQ/ledger-live-desktop#3730]
#### Ledger Live Version and Operating System
- Ledger Live Version **2.24.0**
- Platform and version: **Ubuntu 20.04**

#### Expected behavior
Update should work after downloading clicking `install now`

#### Actual behavior
Nothing it just hangs, tried restarting Ledger Live app, its asks to download again but uses the cached download. I can see `permission denied` in the logs but it not a permission issue because all other updates have worked fine. 

See logs from console.
```
nonroot@colossus:~$ /opt/ledger.AppImage 
Ledger Live 2.24.0
(node:12519) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
init
Checking for update
spawned internal process 12624
Found version 2.25.1 (url: ledger-live-desktop-2.25.1-linux-x86_64.AppImage)
download-update
Downloading update from ledger-live-desktop-2.25.1-linux-x86_64.AppImage
updater cache dir: /home/nonroot/.cache/ledger-live-desktop-updater
Update has already been downloaded to /home/nonroot/.cache/ledger-live-desktop-updater/pending/ledger-live-desktop-2.25.1-linux-x86_64.AppImage).
quit-and-install
Install on explicit quitAndInstall
Install: isSilent: false, isForceRunAfter: true
Error: Error: EACCES: permission denied, unlink '/opt/ledger.AppImage'
    at unlinkSync (fs.js:1140:3)
    at AppImageUpdater.doInstall (/tmp/.mount_ledgerxGSMiR/resources/app.asar/node_modules/@ledgerhq/electron-updater/out/AppImageUpdater.js:146:24)
    at AppImageUpdater.install (/tmp/.mount_ledgerxGSMiR/resources/app.asar/node_modules/@ledgerhq/electron-updater/out/BaseUpdater.js:71:19)
    at AppImageUpdater.quitAndInstall (/tmp/.mount_ledgerxGSMiR/resources/app.asar/node_modules/@ledgerhq/electron-updater/out/BaseUpdater.js:28:30)
    at Object.quitAndInstall (/tmp/.mount_ledgerxGSMiR/resources/app.asar/.webpack/main.bundle.js:4448:36)
    at main_updater (/tmp/.mount_ledgerxGSMiR/resources/app.asar/.webpack/main.bundle.js:902:17)
    at IpcMainImpl.<anonymous> (/tmp/.mount_ledgerxGSMiR/resources/app.asar/.webpack/main.bundle.js:947:3)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
    at Object.emit (events.js:315:20)
```

#### Steps to reproduce the behavior

See above.

**Comment by gre** [comment]
Is this still happening? maybe get latest release from https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.25.1

**Comment by JamesKBowler** [comment]
Hello there, I know I can download the lastest .AppImage, but the click click option is broken.
