### ISSUE TITLE
Impossible to navigate with Ledger live

### ISSUE THREAD

**Issue by Charlie971** [LedgerHQ/ledger-live-desktop#3792]
Hello I m using the last release of Ledger and I have an big issue blocker. I'm trying to create an account for my nano s or see the portfolio. The systen crash every time with this error message. It's possible to fix it ? 

thanks

here the error message below:

tickers.forEach is not a function
TypeError: tickers.forEach is not a function
    at sortByMarketcap (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:123021:11)
    at useCurrenciesByMarketcap (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:123058:20)
    at SelectCurrency (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:361917:69)
    at Ch (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:205972:137)
    at li (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:205995:154)
    at ki (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:205993:169)
    at ck (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206089:157)
    at bk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206065:347)
    at ak (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206065:278)
    at Tj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206065:138)

**Comment by FrankP01** [comment]
> Hello I m using the last release of Ledger and I have an big issue blocker. I'm trying to create an account for my nano s or see the portfolio. The systen crash every time with this error message. It's possible to fix it ?
> 
> thanks
> 
> here the error message below:
> 
> tickers.forEach is not a function
> TypeError: tickers.forEach is not a function
> at sortByMarketcap (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:123021:11)
> at useCurrenciesByMarketcap (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:123058:20)
> at SelectCurrency (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:361917:69)
> at Ch (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:205972:137)
> at li (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:205995:154)
> at ki (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:205993:169)
> at ck (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206089:157)
> at bk (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206065:347)
> at ak (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206065:278)
> at Tj (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:206065:138)

I will advise you contact the ledger support team on telegram it’s helpful and they are active here is the username to contact the support team @ledgersupport0 they will be glad to help you on this .. check it out cheers

**Comment by gre** [comment]
Ledger do not offer telegram support. This is a scam attempt. Official support is support.ledger.com

**Comment by gre** [comment]
@Charlie971 is it still happening? It's the first time I see this issue, i wonder if it was temporary

**Comment by Charlie971** [comment]
hello @gre , still happening on Windows and MAC. i'm trying to follow the solution of the ledger website by installing the C++for windows and delete the ledger folder on the MAc. I re install several time the app by cleaning all the file and registry but still have the same problem

**Comment by Charlie971** [comment]
And I also reset the ledger nano device if it's the device the problenm. But the software continues to crash

**Comment by gre** [comment]
I'm struggled to understand the problem at stack. 
do you have the possibility to Export Logs and them them directly to our customer support team by referring to this github issue?  ( https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165 )

alternatively if you don't want to send the logs , you can see the JSON yourself on https://ledger-live-tools.vercel.app/logsviewer

what i'm interested to see is if there are any HTTP failure, specifically around the countervalues. Are you using any specific proxy or firewall?
