### ISSUE TITLE
ledger live crashes after update 

### ISSUE THREAD

**Issue by Fgregorio1** [LedgerHQ/ledger-live-desktop#4064]
i just updated the my ledger live desktop on my linux debian and i can't run anymore, its crashing. i already tried to delete the .conf/LedgerLive directory and still crashing. this is the log:

Internal process error (1)
Error
    at createCustomErrorClass (file:///tmp/.mount_ledger7STKsz/resources/app.asar/.webpack/renderer.bundle.js:5937:19)
    at deserializeError (file:///tmp/.mount_ledger7STKsz/resources/app.asar/.webpack/renderer.bundle.js:5965:35)
    at EventEmitter.handleCommandEvent (file:///tmp/.mount_ledger7STKsz/resources/app.asar/.webpack/renderer.bundle.js:544205:61)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)

and this is the output on my terminal:

**./ledger-live-desktop-*.AppImage --no-sandbox**        
Ledger Live 2.31.1
(node:27706) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
init
Checking for update
spawned internal process 27803
Update for version 2.31.1 is not available (latest version: 2.31.1, downgrade is disallowed).
internal process 27803 gracefully exited with code 1

any suggestion to solve this problem? thanks

**Comment by jonklinger** [comment]
also for me, updated from 2.29 to 2.31 and everything crashed. 2.30 doesn't work as well

**Comment by vnegi10** [comment]
Same here. This seems like a known [issue](https://support.ledger.com/hc/en-us/articles/360012598060?utm_source=ledger_live_desktop&utm_medium=self_referral&utm_content=error&support=true), but I couldn't find a solution or a workaround.


Versions **2.30.0** and **2.31.1** crash with an error log as shown below. **2.29.0** is okay, but I would like to update in order to resolve issues with my DOT wallet.



**OS:** elementary OS 5.1.7 Hera x86_64, **Kernel:** 5.4.0-74-generic 

**Error log:**
Internal process error (1)
Error
    at createCustomErrorClass (file:///tmp/.mount_ledger7PkINY/resources/app.asar/.webpack/renderer.bundle.js:11608:19)
    at deserializeError (file:///tmp/.mount_ledger7PkINY/resources/app.asar/.webpack/renderer.bundle.js:11636:35)
    at EventEmitter.handleCommandEvent (file:///tmp/.mount_ledger7PkINY/resources/app.asar/.webpack/renderer.bundle.js:461212:61)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)

**Comment by bahbarnett** [comment]
Ledger is well aware of this issue, and they have apparently decided to stop supporting the majority of Linux distros ; Debian Stable, anything derived from Debian Stable, and reportedly a large number of other non-Debian based distros.  

They state there here, with an official Ledger support account:

https://www.reddit.com/r/ledgerwallet/comments/oua6u4/ledger_live_2311_crashing/h72eg9h/

Meanwhile, their webpage (almost a month later) says they are 'aware of the issue and working on it'.  My take on this, is their DEV team just decided to arbitrarily upgrade a glibc dependency, not check how much of an issue it would be to their Linux user base, and apparently don't even test on more than a few distros.

Something which is easy with a VM cluster and automated testing.

**Comment by jimbowarrior** [comment]
Upgrade to Debian11 fixed the issue.
Debian 11 should be release in 2 weeks, in my opinion you don't take a risk to upgrade a desktop environment ...

**Comment by bahbarnett** [comment]
> Upgrade to Debian11 fixed the issue.
> Debian 11 should be release in 2 weeks, in my opinion you don't take a risk to upgrade a desktop environment ...

While Bullseye may fix the issue, that's not the point.

First?  

This release date was set weeks after they broke on Debian Stable.  They had no idea when it would be fixed, it could literally have been months.  Yet they told NO ONE this, have not even yet indicated what a all of these users need to do.  No place on their website do they say "Oh, you need to do $x, because of $y".

Instead, they say they're "Working on it".  Wow.  Great customer support, that is.

This is a core, user support failure.  And it is very clear from their initial response, that they had no idea, no testing, that they just started to receive bug reports from a load of Linux users.  So please, don't defend this decision of theirs, as if it's not a big deal.

It's about *how* they are handling this, as much as them mucking up.  

Second?

This "fix" doesn't cover all Debian based distros.  Just because Debian *may* release in a week or two, as announced, doesn't mean everyone will rebase in 5 minutes.  On top of this, many users need stability, and time.

Not only do I personally wait until .1 of a new Debian release, as there are (naturally) all sorts of usability bugs found in the first couple of months, but upgrading a desktop does have risk.  Apps can stop working, there are config changes, and generally a new workflow you may have to get used to.  

Thus, many users *set time aside*, for they cannot be "down" during a workday.  They can't just upgrade on a whim, because they might run into issues, and need hours or days to end up at a full stable, and workable desktop again.

Regardless of whether you personally feel this way, many users do.  I know, I support them.  I don't think it's very unfair to, as an app developer, think "OK, Debian Stable should be out in a few weeks.  Everyone won't upgrade within 10 minutes.  Likely, it will take a month or two for people to get around to upgrading".

Thus, this too is a major failure point.  The sheer audacity, the sheer balls of thinking that *their little app* is *so important*, that everyone should just drop what they're doing, upgrade everything *just for them*, because *oh well, get over it, you can use the app again in a few months* is just absurd beyond belief.

By the way, my anger is not at you jimbowarrior.  But my rebuttal of your comment is vital here.  In my opinion, you are giving solace to those which are not behaving correctly.

Please understand my position.  This is a financial app.  This is an app people use to check their funds, transfer funds, and even pay for goods and services.  Ledger's support needs to be thinking in terms of *decade long* release cycles.

They need to be thinking "When are banks down, that's how we should be." 

Consider this ; their app is not about *new fluff*, but *about always working, and working correctly*.

Or, do you want your eth/bc/whatever being sent to the wrong address? No, this app is about stable, stable, stable.

They need to get their heads on right.

**Comment by Ratio2** [comment]
All this issues has same error reason:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found
#4016
#4023
#4041
#4064

Actually 2.30/2.31.1 versions not work on:
Debian stable
Ubuntu 18.04 LTS
And many other latest distro...

Ledger, what are you waiting for? Just rebuild the application with the previous environment like 2.29.

**Comment by gre** [comment]
> Ledger, what are you waiting for? Just rebuild the application with the previous environment like 2.29.

The issue at stake here is that the environment used to build 2.29 is no longer an option :(
Polkadot dependency raised their required node version to 14. We were still building with node 12. There is a collision with one internal CPP library we use (libcore) that seems to create the problem, more investigation need to be done on this.

Maintaining software is hard, we'll do our best to find solution, we do test on a few Linux distributions but we're going to increase our coverage to detect such problem earlier. unfortunately this issue only happens in specific setup that was not on the main ones we were covering by our current automation.

**Comment by Ratio2** [comment]
> unfortunately this issue only happens in specific setup that was not on the main ones we were covering by our current automation.
Debian stable is not a specific setup, it is the most important distribution.

**Comment by epicTreeStick** [comment]
I have ubuntu 18.04 lts, here's what I get in the CLI when trying to run 2.31.1:
```
 internal process 3886 gracefully exited with code 1
(node:3775) UnhandledPromiseRejectionWarning: Error: Process not running
    at /tmp/.mount_ledgeroQoJ7f/resources/app.asar/.webpack/main.bundle.js:3378:16
    at new Promise (<anonymous>)
    at InternalProcess_InternalProcess.stop (/tmp/.mount_ledgeroQoJ7f/resources/app.asar/.webpack/main.bundle.js:3376:12)
    at App.<anonymous> (/tmp/.mount_ledgeroQoJ7f/resources/app.asar/.webpack/main.bundle.js:3462:20)
    at App.emit (events.js:327:22)
(node:3775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I get this error in the window of the app:
```
Internal process error (1)
Error
    at createCustomErrorClass (file:///tmp/.mount_ledgermndMWM/resources/app.asar/.webpack/renderer.bundle.js:5937:19)
    at deserializeError (file:///tmp/.mount_ledgermndMWM/resources/app.asar/.webpack/renderer.bundle.js:5965:35)
    at EventEmitter.handleCommandEvent (file:///tmp/.mount_ledgermndMWM/resources/app.asar/.webpack/renderer.bundle.js:544205:61)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
```
I also tried deleting the contents of "~/.config/Ledger\ Live" as per this:
https://support.ledger.com/hc/en-us/articles/360012598060?utm_source=ledger_live_desktop&utm_medium=self_referral&utm_content=error&support=true

Which didn't make any difference.
Best of luck!

**Comment by WarAgainstWorld** [comment]
The same problem on Linux Mint 19.3 Tricia

**Comment by gre** [comment]
Hey everyone. We put together a release (2.32.2) that should fix it and is planned to be released about a week from now (we'll first release a 2.32.1 because we'll need more time to continue validating that 2.32.2).

This is currently a **Pre-release** (please consider it a release candidate version until we finish to validate it), we have at least confirmed internally it is fixed on a Debian, but it is still interesting to hear if it also fixes it for y'all. Thanks a lot.

https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.32.2

**Comment by inzider** [comment]
I had the issue on Ubuntu 18, previous post did the job: https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.32.2.
Thanks a lot!

**Comment by Fgregorio1** [comment]
> Hey everyone. We put together a release (2.32.2) that should fix it and is planned to be released about a week from now (we'll first release a 2.32.1 because we'll need more time to continue validating that 2.32.2).
> 
> This is currently a **Pre-release** (please consider it a release candidate version until we finish to validate it), we have at least confirmed internally it is fixed on a Debian, but it is still interesting to hear if it also fixes it for y'all. Thanks a lot.
> 
> https://github.com/LedgerHQ/ledger-live-desktop/releases/tag/v2.32.2

it worked !!! Thank you
