### ISSUE TITLE
2.36.2 installed via winget repo and 2.36.3 installed from .exe dl'ed from website fail to run - 'internal process error'

### ISSUE THREAD

**Issue by leonwear** [LedgerHQ/ledger-live-desktop#4570]
#### Ledger Live Version and Operating System

- tested on Ledger Live **version_here**
- 2.36.2 & 2.36.3
- Platform and version: **e.g. Mac 10.13.5 / Windows 10 / ..**
- Windows 11 Pro 21H2 22000.376

#### Expected behavior

Ledger Live should load.

#### Actual behavior

Internal process error (1)
Error
    at createCustomErrorClass (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:5296:19)
    at deserializeError (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:5324:35)
    at EventEmitter.handleCommandEvent (file:///C:/Program%20Files/Ledger%20Live/resources/app.asar/.webpack/renderer.bundle.js:665792:61)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:93:1117)

#### Steps to reproduce the behavior
Install and run. Is Win11 not yet supported?

**Comment by leonwear** [comment]
Similar to https://github.com/LedgerHQ/ledger-live-desktop/issues/2680?

**Comment by leonwear** [comment]
![image](https://user-images.githubusercontent.com/47862275/147097187-3a7c2c97-1714-4efb-a691-7f78bdac4e4e.png)

**Comment by leonwear** [comment]
Log export:
[ledgerlive-logs-2021.12.22-13.10.54-4b32315.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/7762806/ledgerlive-logs-2021.12.22-13.10.54-4b32315.txt)

**Comment by leonwear** [comment]
Log export with Win7 compatability mode:
[ledgerlive-logs-2021.12.22-13.08.49-4b32315.txt](https://github.com/LedgerHQ/ledger-live-desktop/files/7762810/ledgerlive-logs-2021.12.22-13.08.49-4b32315.txt)

**Comment by kevinwmerritt** [comment]
Also experiencing this error with Windows 11 Pro.
