### ISSUE TITLE
Unable to add any cosmos account on last ledger live / firmware

### ISSUE THREAD

**Issue by Milerius** [LedgerHQ/ledger-live-desktop#4720]
<img width="563" alt="Capture d’écran 2022-02-05 à 18 17 57" src="https://user-images.githubusercontent.com/21139416/152651850-afedea56-cc0c-43c4-8399-ae11e39c6c3a.png">

^

**Comment by kathodler** [comment]
Can confirm this. Looking at the json log it appears there is a 500 error from the txs call. 

Notable log errors:

```
{
    "stack": "Error\n    at createCustomErrorClass (/tmp/.mount_ledgerFJdobj/resources/app.asar/node_modules/@ledgerhq/errors/lib/helpers.js:32:19)\n    at Object.<anonymous> (/tmp/.mount_ledgerFJdobj/resources/app.asar/node_modules/@ledgerhq/errors/lib/index.js:100:61)\n    at Module._compile (internal/modules/cjs/loader.js:1078:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)\n    at Module.load (internal/modules/cjs/loader.js:935:32)\n    at Module._load (internal/modules/cjs/loader.js:776:14)\n    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)\n    at Module.require (internal/modules/cjs/loader.js:959:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at Object.<anonymous> (/tmp/.mount_ledgerFJdobj/resources/app.asar/node_modules/@ledgerhq/live-common/lib/network.js:10:16)",
    "message": "API HTTP 500 API HTTP 500",
    "name": "LedgerAPI5xx",
    "level": "info",
    "pname": "renderer",
    "timestamp": "2022-03-20T04:36:07.233Z"
  },
```

```
 {
    "type": "network-error",
    "message": "500 get https://cosmoshub4.coin.ledger.com/txs?tx.minheight=0&transfer.recipient=<INSERT_COSMOS_ADDRESS_HERE>&page=1&limit=100 (17882ms): API HTTP 500",
    "data": {},
    "level": "debug",
    "pname": "internal",
    "timestamp": "2022-03-20T04:36:07.231Z"
  },
```

```
  {
    "type": "warn",
    "message": "can't parse server result SyntaxError: Unexpected token h in JSON at position 1",
    "level": "debug",
    "pname": "internal",
    "timestamp": "2022-03-20T04:36:07.230Z"
  },```

**Comment by kathodler** [comment]
Going directly to the link above will 500 with an error message about gRPC:

```
{"error":"this transaction cannot be displayed via legacy REST endpoints, because it does not support Amino serialization. Please either use CLI, gRPC, gRPC-gateway, or directly query the Tendermint RPC endpoint to query this transaction. The new REST endpoint (via gRPC-gateway) is /cosmos/tx/v1beta1/txs. Please also see theREST endpoints migration guide at https://docs.cosmos.network/master/migrations/rest.html for more info"}
```

My guess is that ledger live was using the REST API and cosmos upgraded to use gRPC but I am not 100% sure.

**Comment by kathodler** [comment]
This could be sidestepped if this (now old) issue was implemented https://github.com/LedgerHQ/ledger-live-desktop/issues/3826
