### ISSUE TITLE
macOS: Internal process error (null)

### ISSUE THREAD

**Issue by outdeh** [LedgerHQ/ledger-live-desktop#990]
Hello Ledger Support,

I tried installing and running Ledger Live on my Mac today and every time I launch it I receive an error, "Oops, something went wrong." I uninstalled, re-installed, and still every time I receive the error shortly after it launches. I'm running Mac OS X version 10.11.6. Thank you for any assistance. The error logs are below.

[ledgerlive-export-2018.07.09-20.15.19-c7c5c51e1dd0136251485114e6020ab354789a23.log](https://github.com/LedgerHQ/ledger-live-desktop/files/2178727/ledgerlive-export-2018.07.09-20.15.19-c7c5c51e1dd0136251485114e6020ab354789a23.log)
Error was thrown:

```
Error
    at o (file:///Applications/Ledger%20Live.app/Contents/Resources/app.asar/renderer.js:1:25413)
    at a (file:///Applications/Ledger%20Live.app/Contents/Resources/app.asar/renderer.js:1:25600)
    at EventEmitter.l (file:///Applications/Ledger%20Live.app/Contents/Resources/app.asar/renderer.js:1:27016)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
```

**Comment by gre** [comment]
in the upcoming 1.0.2: might be fixed by @KhalilBellakrid  (mac build).
