### ISSUE TITLE
Error: Internal process error (null)

### ISSUE THREAD

**Issue by edupin2** [LedgerHQ/ledger-live-desktop#999]
The error is shown on mac OS X 10.11. El Capitan

Error was thrown:

```
Error
    at o (file:///Applications/Ledger%20Live.app/Contents/Resources/app.asar/renderer.js:1:25413)
    at a (file:///Applications/Ledger%20Live.app/Contents/Resources/app.asar/renderer.js:1:25600)
    at EventEmitter.l (file:///Applications/Ledger%20Live.app/Contents/Resources/app.asar/renderer.js:1:27016)
    at emitTwo (events.js:130:20)
    at EventEmitter.emit (events.js:213:7)
```

**Comment by meriadec** [comment]
duplicate of https://github.com/LedgerHQ/ledger-live-desktop/issues/990 (more detailed)
